### PR TITLE
Add double buffering for data printing

### LINKED ISSUE #16: Output buffering
The performance of the overall simulation can be improved by buffering the result data and outputting them only once in a while.
An appropriate size of the buffer should be determined.

### PR DESCRIPTION
**Pull request by mscuttari**

### CODE REVIEW

**Comment by mscuttari** [comment]
@thaugdahl I've added a first draft for double buffering the output values. For now the buffer is filled sequentially, but the infrastructure is designed to easily switch to a multithreaded solution. It would be nice if you can try it out and see how the performance is.

**Comment by thaugdahl** [comment]
Performance impact is negligible. This approach should enable some nicer buffered and/or parallel I/O in the future. LGTM.

**Review by thaugdahl — DISMISSED** [review]
LGTM

**Pull request merged**
